// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MasterData module
	public static void aCT_Brand_Save(IContext context, masterdata.proxies.Brand _brand)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Brand", _brand == null ? null : _brand.getMendixObject());
		Core.microflowCall("MasterData.ACT_Brand_Save").withParams(params).execute(context);
	}
	public static void aCT_City_Sync(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MasterData.ACT_City_Sync").withParams(params).execute(context);
	}
	public static void aCT_Motorcycle_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MasterData.ACT_Motorcycle_New").withParams(params).execute(context);
	}
	public static void aCT_State_Sync(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MasterData.ACT_State_Sync").withParams(params).execute(context);
	}
	public static void aCT_TemplateDocument_Vehicle_Save(IContext context, excelimporter.proxies.TemplateDocument _templateDocument)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TemplateDocument", _templateDocument == null ? null : _templateDocument.getMendixObject());
		Core.microflowCall("MasterData.ACT_TemplateDocument_Vehicle_Save").withParams(params).execute(context);
	}
	public static void aCT_Vehicle_Edit(IContext context, masterdata.proxies.Vehicle _vehicle)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Vehicle", _vehicle == null ? null : _vehicle.getMendixObject());
		Core.microflowCall("MasterData.ACT_Vehicle_Edit").withParams(params).execute(context);
	}
	public static void aCT_Vehicle_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MasterData.ACT_Vehicle_New").withParams(params).execute(context);
	}
	public static void aCT_Vehicle_NewImport(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MasterData.ACT_Vehicle_NewImport").withParams(params).execute(context);
	}
	public static void aCT_Vehicle_Save(IContext context, masterdata.proxies.Vehicle _vehicle)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Vehicle", _vehicle == null ? null : _vehicle.getMendixObject());
		Core.microflowCall("MasterData.ACT_Vehicle_Save").withParams(params).execute(context);
	}
	public static void aCT_Vehicle_SendToService(IContext context, masterdata.proxies.Vehicle _vehicle)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Vehicle", _vehicle == null ? null : _vehicle.getMendixObject());
		Core.microflowCall("MasterData.ACT_Vehicle_SendToService").withParams(params).execute(context);
	}
	public static void aCT_VehicleUnit_Save(IContext context, masterdata.proxies.VehicleUnit _vehicleUnit)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("VehicleUnit", _vehicleUnit == null ? null : _vehicleUnit.getMendixObject());
		Core.microflowCall("MasterData.ACT_VehicleUnit_Save").withParams(params).execute(context);
	}
	public static masterdata.proxies.Brand sUB_Brand_GetCreate(IContext context, rest.proxies.Root _root)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Root", _root == null ? null : _root.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("MasterData.SUB_Brand_GetCreate").withParams(params).execute(context);
		return result == null ? null : masterdata.proxies.Brand.initialize(context, result);
	}
	public static boolean vAL_Vehicle(IContext context, masterdata.proxies.Vehicle _vehicle)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Vehicle", _vehicle == null ? null : _vehicle.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MasterData.VAL_Vehicle").withParams(params).execute(context);
	}
	public static boolean vAL_VehicleUnit(IContext context, masterdata.proxies.VehicleUnit _vehicleUnit)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("VehicleUnit", _vehicleUnit == null ? null : _vehicleUnit.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("MasterData.VAL_VehicleUnit").withParams(params).execute(context);
	}
}
