// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rencar.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Rencar module
	public static void aCT_Account_Activate(IContext context, java.lang.String _token)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Token", _token);
		Core.microflowCall("Rencar.ACT_Account_Activate").withParams(params).execute(context);
	}
	public static void aCT_CarSearch_Filter(IContext context, rencar.proxies.CarSearch _carSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CarSearch", _carSearch == null ? null : _carSearch.getMendixObject());
		Core.microflowCall("Rencar.ACT_CarSearch_Filter").withParams(params).execute(context);
	}
	public static void aCT_Contract_DeliverToday(IContext context, rencar.proxies.Contract _contract)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Contract", _contract == null ? null : _contract.getMendixObject());
		Core.microflowCall("Rencar.ACT_Contract_DeliverToday").withParams(params).execute(context);
	}
	public static void aCT_Contract_ExportToExcell(IContext context, rencar.proxies.ContractSearch _contractSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ContractSearch", _contractSearch == null ? null : _contractSearch.getMendixObject());
		Core.microflowCall("Rencar.ACT_Contract_ExportToExcell").withParams(params).execute(context);
	}
	public static void aCT_Contract_New(IContext context, masterdata.proxies.VehicleUnit _vehicleUnit)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("VehicleUnit", _vehicleUnit == null ? null : _vehicleUnit.getMendixObject());
		Core.microflowCall("Rencar.ACT_Contract_New").withParams(params).execute(context);
	}
	public static void aCT_Contract_Postpone_Save(IContext context, rencar.proxies.Contract _contract)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Contract", _contract == null ? null : _contract.getMendixObject());
		Core.microflowCall("Rencar.ACT_Contract_Postpone_Save").withParams(params).execute(context);
	}
	public static void aCT_Contract_Save(IContext context, rencar.proxies.Contract _contract)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Contract", _contract == null ? null : _contract.getMendixObject());
		Core.microflowCall("Rencar.ACT_Contract_Save").withParams(params).execute(context);
	}
	public static void aCT_Contract_Search(IContext context, rencar.proxies.ContractSearch _contractSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("ContractSearch", _contractSearch == null ? null : _contractSearch.getMendixObject());
		Core.microflowCall("Rencar.ACT_Contract_Search").withParams(params).execute(context);
	}
	public static void aCT_DashboardHelper_Save(IContext context, rencar.proxies.DashboardHelper _dashboardHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardHelper", _dashboardHelper == null ? null : _dashboardHelper.getMendixObject());
		Core.microflowCall("Rencar.ACT_DashboardHelper_Save").withParams(params).execute(context);
	}
	public static void aCT_DeliveryAddress_Del(IContext context, rencar.proxies.DeliveryAddress _deliveryAddress, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DeliveryAddress", _deliveryAddress == null ? null : _deliveryAddress.getMendixObject());
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("Rencar.ACT_DeliveryAddress_Del").withParams(params).execute(context);
	}
	public static void aCT_DeliveryAddress_New(IContext context, administration.proxies.Account _account)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Account", _account == null ? null : _account.getMendixObject());
		Core.microflowCall("Rencar.ACT_DeliveryAddress_New").withParams(params).execute(context);
	}
	public static void aCT_DeliveryAddress_Save(IContext context, rencar.proxies.DeliveryAddress _deliveryAddress)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DeliveryAddress", _deliveryAddress == null ? null : _deliveryAddress.getMendixObject());
		Core.microflowCall("Rencar.ACT_DeliveryAddress_Save").withParams(params).execute(context);
	}
	public static void aCT_Login_SignUp_New(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Rencar.ACT_Login_SignUp_New").withParams(params).execute(context);
	}
	public static void aCT_SignUp_Save(IContext context, rencar.proxies.SignUp _signUp)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SignUp", _signUp == null ? null : _signUp.getMendixObject());
		Core.microflowCall("Rencar.ACT_SignUp_Save").withParams(params).execute(context);
	}
	public static void anonymous_Home_Web(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Rencar.Anonymous_Home_Web").withParams(params).execute(context);
	}
	public static void contract_GenerateExcel(IContext context, xlsreport.proxies.MxTemplate _template, rencar.proxies.ContractSearch _contractSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Template", _template == null ? null : _template.getMendixObject());
		params.put("ContractSearch", _contractSearch == null ? null : _contractSearch.getMendixObject());
		Core.microflowCall("Rencar.Contract_GenerateExcel").withParams(params).execute(context);
	}
	public static void contract_NotifyClients(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Rencar.Contract_NotifyClients").withParams(params).execute(context);
	}
	public static void contract_SendEmail(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate, rencar.proxies.EmailContent _emailContent, java.lang.String _email, rencar.proxies.ContractSummary _contractSummary)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		params.put("EmailContent", _emailContent == null ? null : _emailContent.getMendixObject());
		params.put("Email", _email);
		params.put("ContractSummary", _contractSummary == null ? null : _contractSummary.getMendixObject());
		Core.microflowCall("Rencar.Contract_SendEmail").withParams(params).execute(context);
	}
	public static void contract_SendReminder(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate, rencar.proxies.EmailContent _emailContent, java.lang.String _email)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		params.put("EmailContent", _emailContent == null ? null : _emailContent.getMendixObject());
		params.put("Email", _email);
		Core.microflowCall("Rencar.Contract_SendReminder").withParams(params).execute(context);
	}
	public static rencar.proxies.CarSearch dS_CarSearch(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Rencar.DS_CarSearch").withParams(params).execute(context);
		return result == null ? null : rencar.proxies.CarSearch.initialize(context, result);
	}
	public static rencar.proxies.ContractSearch dS_ContractSearch(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Rencar.DS_ContractSearch").withParams(params).execute(context);
		return result == null ? null : rencar.proxies.ContractSearch.initialize(context, result);
	}
	public static java.util.List<rencar.proxies.Value> dS_Value(IContext context, rencar.proxies.DashboardHelper _dashboardHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardHelper", _dashboardHelper == null ? null : _dashboardHelper.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("Rencar.DS_Value").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> rencar.proxies.Value.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void home_ResponsiveProfile(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Rencar.Home_ResponsiveProfile").withParams(params).execute(context);
	}
	public static void login_SignUp_SendEmail(IContext context, emailtemplate.proxies.EmailTemplate _emailTemplate, rencar.proxies.EmailContent _emailContent, java.lang.String _email)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("EmailTemplate", _emailTemplate == null ? null : _emailTemplate.getMendixObject());
		params.put("EmailContent", _emailContent == null ? null : _emailContent.getMendixObject());
		params.put("Email", _email);
		Core.microflowCall("Rencar.Login_SignUp_SendEmail").withParams(params).execute(context);
	}
	public static void nAV_Dashboard_Open(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Rencar.NAV_Dashboard_Open").withParams(params).execute(context);
	}
	public static void oCH_Contract_Date(IContext context, rencar.proxies.Contract _contract)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Contract", _contract == null ? null : _contract.getMendixObject());
		Core.microflowCall("Rencar.OCH_Contract_Date").withParams(params).execute(context);
	}
	public static void oCH_DeliveryAddress_GetPostalCode(IContext context, rencar.proxies.DeliveryAddress _deliveryAddress)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DeliveryAddress", _deliveryAddress == null ? null : _deliveryAddress.getMendixObject());
		Core.microflowCall("Rencar.OCH_DeliveryAddress_GetPostalCode").withParams(params).execute(context);
	}
	public static boolean sUB_Contract_Date(IContext context, rencar.proxies.Contract _contract)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Contract", _contract == null ? null : _contract.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Rencar.SUB_Contract_Date").withParams(params).execute(context);
	}
	public static void sUB_DashboardHelper_BarChart(IContext context, rencar.proxies.DashboardHelper _dashboardHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardHelper", _dashboardHelper == null ? null : _dashboardHelper.getMendixObject());
		Core.microflowCall("Rencar.SUB_DashboardHelper_BarChart").withParams(params).execute(context);
	}
	public static void sUB_DashboardHelper_CalculateKPIs(IContext context, rencar.proxies.DashboardHelper _dashboardHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardHelper", _dashboardHelper == null ? null : _dashboardHelper.getMendixObject());
		Core.microflowCall("Rencar.SUB_DashboardHelper_CalculateKPIs").withParams(params).execute(context);
	}
	public static rencar.proxies.DashboardHelper sUB_DashboardHelper_GetCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("Rencar.SUB_DashboardHelper_GetCreate").withParams(params).execute(context);
		return result == null ? null : rencar.proxies.DashboardHelper.initialize(context, result);
	}
	public static void sUB_DashboardHelper_GetData(IContext context, rencar.proxies.DashboardHelper _dashboardHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardHelper", _dashboardHelper == null ? null : _dashboardHelper.getMendixObject());
		Core.microflowCall("Rencar.SUB_DashboardHelper_GetData").withParams(params).execute(context);
	}
	public static void sUB_DashboardHelper_GetProgressCircle(IContext context, rencar.proxies.DashboardHelper _dashboardHelper)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardHelper", _dashboardHelper == null ? null : _dashboardHelper.getMendixObject());
		Core.microflowCall("Rencar.SUB_DashboardHelper_GetProgressCircle").withParams(params).execute(context);
	}
	public static boolean sUB_DeliveryAddress(IContext context, rencar.proxies.DeliveryAddress _deliveryAddress)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DeliveryAddress", _deliveryAddress == null ? null : _deliveryAddress.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Rencar.SUB_DeliveryAddress").withParams(params).execute(context);
	}
	public static boolean sUB_Login_SigUp_Valid(IContext context, rencar.proxies.SignUp _signUp)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SignUp", _signUp == null ? null : _signUp.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("Rencar.SUB_Login_SigUp_Valid").withParams(params).execute(context);
	}
	public static rencar.proxies.CarSearch vAL_Contract_Vehicle(IContext context, rencar.proxies.CarSearch _carSearch)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CarSearch", _carSearch == null ? null : _carSearch.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Rencar.VAL_Contract_Vehicle").withParams(params).execute(context);
		return result == null ? null : rencar.proxies.CarSearch.initialize(context, result);
	}
	public static rencar.proxies.CarSearch vAL_Contract_Vehicle_Postpone(IContext context, rencar.proxies.CarSearch _carSearch, rencar.proxies.Contract _contract)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CarSearch", _carSearch == null ? null : _carSearch.getMendixObject());
		params.put("Contract", _contract == null ? null : _contract.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("Rencar.VAL_Contract_Vehicle_Postpone").withParams(params).execute(context);
		return result == null ? null : rencar.proxies.CarSearch.initialize(context, result);
	}
}
