// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rencar.proxies;

public class Contract
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject contractMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Rencar.Contract";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StartDate("StartDate"),
		EndDate("EndDate"),
		TotalPrice("TotalPrice"),
		HasComments("HasComments"),
		Comments("Comments"),
		Contract_ContractSearch("Rencar.Contract_ContractSearch"),
		Contract_Account("Rencar.Contract_Account"),
		Contract_VehicleUnit("Rencar.Contract_VehicleUnit");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Contract(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Contract(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject contractMendixObject)
	{
		if (contractMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, contractMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.contractMendixObject = contractMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Contract.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rencar.proxies.Contract initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rencar.proxies.Contract.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static rencar.proxies.Contract initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rencar.proxies.Contract(context, mendixObject);
	}

	public static rencar.proxies.Contract load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rencar.proxies.Contract.initialize(context, mendixObject);
	}

	public static java.util.List<rencar.proxies.Contract> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> rencar.proxies.Contract.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice()
	{
		return getTotalPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalPrice.toString());
	}

	/**
	 * Set value of TotalPrice
	 * @param totalprice
	 */
	public final void setTotalPrice(java.math.BigDecimal totalprice)
	{
		setTotalPrice(getContext(), totalprice);
	}

	/**
	 * Set value of TotalPrice
	 * @param context
	 * @param totalprice
	 */
	public final void setTotalPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalprice)
	{
		getMendixObject().setValue(context, MemberNames.TotalPrice.toString(), totalprice);
	}

	/**
	 * @return value of HasComments
	 */
	public final java.lang.Boolean getHasComments()
	{
		return getHasComments(getContext());
	}

	/**
	 * @param context
	 * @return value of HasComments
	 */
	public final java.lang.Boolean getHasComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasComments.toString());
	}

	/**
	 * Set value of HasComments
	 * @param hascomments
	 */
	public final void setHasComments(java.lang.Boolean hascomments)
	{
		setHasComments(getContext(), hascomments);
	}

	/**
	 * Set value of HasComments
	 * @param context
	 * @param hascomments
	 */
	public final void setHasComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hascomments)
	{
		getMendixObject().setValue(context, MemberNames.HasComments.toString(), hascomments);
	}

	/**
	 * @return value of Comments
	 */
	public final java.lang.String getComments()
	{
		return getComments(getContext());
	}

	/**
	 * @param context
	 * @return value of Comments
	 */
	public final java.lang.String getComments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comments.toString());
	}

	/**
	 * Set value of Comments
	 * @param comments
	 */
	public final void setComments(java.lang.String comments)
	{
		setComments(getContext(), comments);
	}

	/**
	 * Set value of Comments
	 * @param context
	 * @param comments
	 */
	public final void setComments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comments)
	{
		getMendixObject().setValue(context, MemberNames.Comments.toString(), comments);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Contract_ContractSearch
	 */
	public final java.util.List<rencar.proxies.ContractSearch> getContract_ContractSearch() throws com.mendix.core.CoreException
	{
		return getContract_ContractSearch(getContext());
	}

	/**
	 * @param context
	 * @return value of Contract_ContractSearch
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<rencar.proxies.ContractSearch> getContract_ContractSearch(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<rencar.proxies.ContractSearch> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Contract_ContractSearch.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(rencar.proxies.ContractSearch.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Contract_ContractSearch
	 * @param contract_contractsearch
	 */
	public final void setContract_ContractSearch(java.util.List<rencar.proxies.ContractSearch> contract_contractsearch)
	{
		setContract_ContractSearch(getContext(), contract_contractsearch);
	}

	/**
	 * Set value of Contract_ContractSearch
	 * @param context
	 * @param contract_contractsearch
	 */
	public final void setContract_ContractSearch(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<rencar.proxies.ContractSearch> contract_contractsearch)
	{
		var identifiers = contract_contractsearch
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Contract_ContractSearch.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Contract_Account
	 */
	public final administration.proxies.Account getContract_Account() throws com.mendix.core.CoreException
	{
		return getContract_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Contract_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getContract_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Contract_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Contract_Account
	 * @param contract_account
	 */
	public final void setContract_Account(administration.proxies.Account contract_account)
	{
		setContract_Account(getContext(), contract_account);
	}

	/**
	 * Set value of Contract_Account
	 * @param context
	 * @param contract_account
	 */
	public final void setContract_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account contract_account)
	{
		if (contract_account == null) {
			getMendixObject().setValue(context, MemberNames.Contract_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Contract_Account.toString(), contract_account.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Contract_VehicleUnit
	 */
	public final masterdata.proxies.VehicleUnit getContract_VehicleUnit() throws com.mendix.core.CoreException
	{
		return getContract_VehicleUnit(getContext());
	}

	/**
	 * @param context
	 * @return value of Contract_VehicleUnit
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.VehicleUnit getContract_VehicleUnit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.VehicleUnit result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Contract_VehicleUnit.toString());
		if (identifier != null) {
			result = masterdata.proxies.VehicleUnit.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Contract_VehicleUnit
	 * @param contract_vehicleunit
	 */
	public final void setContract_VehicleUnit(masterdata.proxies.VehicleUnit contract_vehicleunit)
	{
		setContract_VehicleUnit(getContext(), contract_vehicleunit);
	}

	/**
	 * Set value of Contract_VehicleUnit
	 * @param context
	 * @param contract_vehicleunit
	 */
	public final void setContract_VehicleUnit(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.VehicleUnit contract_vehicleunit)
	{
		if (contract_vehicleunit == null) {
			getMendixObject().setValue(context, MemberNames.Contract_VehicleUnit.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Contract_VehicleUnit.toString(), contract_vehicleunit.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return contractMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rencar.proxies.Contract that = (rencar.proxies.Contract) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
