// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rencar.proxies;

public class Value
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject valueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Rencar.Value";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		xValue("xValue"),
		yValue("yValue"),
		BubbleSize("BubbleSize"),
		Value_Series("Rencar.Value_Series"),
		Value_DashboardHelper("Rencar.Value_DashboardHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Value(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Value(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject valueMendixObject)
	{
		if (valueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, valueMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.valueMendixObject = valueMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Value.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rencar.proxies.Value initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rencar.proxies.Value.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static rencar.proxies.Value initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rencar.proxies.Value(context, mendixObject);
	}

	public static rencar.proxies.Value load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rencar.proxies.Value.initialize(context, mendixObject);
	}

	public static java.util.List<rencar.proxies.Value> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> rencar.proxies.Value.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of xValue
	 */
	public final java.lang.String getxValue()
	{
		return getxValue(getContext());
	}

	/**
	 * @param context
	 * @return value of xValue
	 */
	public final java.lang.String getxValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.xValue.toString());
	}

	/**
	 * Set value of xValue
	 * @param xvalue
	 */
	public final void setxValue(java.lang.String xvalue)
	{
		setxValue(getContext(), xvalue);
	}

	/**
	 * Set value of xValue
	 * @param context
	 * @param xvalue
	 */
	public final void setxValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xvalue)
	{
		getMendixObject().setValue(context, MemberNames.xValue.toString(), xvalue);
	}

	/**
	 * @return value of yValue
	 */
	public final java.lang.Integer getyValue()
	{
		return getyValue(getContext());
	}

	/**
	 * @param context
	 * @return value of yValue
	 */
	public final java.lang.Integer getyValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.yValue.toString());
	}

	/**
	 * Set value of yValue
	 * @param yvalue
	 */
	public final void setyValue(java.lang.Integer yvalue)
	{
		setyValue(getContext(), yvalue);
	}

	/**
	 * Set value of yValue
	 * @param context
	 * @param yvalue
	 */
	public final void setyValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer yvalue)
	{
		getMendixObject().setValue(context, MemberNames.yValue.toString(), yvalue);
	}

	/**
	 * @return value of BubbleSize
	 */
	public final java.lang.Integer getBubbleSize()
	{
		return getBubbleSize(getContext());
	}

	/**
	 * @param context
	 * @return value of BubbleSize
	 */
	public final java.lang.Integer getBubbleSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BubbleSize.toString());
	}

	/**
	 * Set value of BubbleSize
	 * @param bubblesize
	 */
	public final void setBubbleSize(java.lang.Integer bubblesize)
	{
		setBubbleSize(getContext(), bubblesize);
	}

	/**
	 * Set value of BubbleSize
	 * @param context
	 * @param bubblesize
	 */
	public final void setBubbleSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer bubblesize)
	{
		getMendixObject().setValue(context, MemberNames.BubbleSize.toString(), bubblesize);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Value_Series
	 */
	public final rencar.proxies.Series getValue_Series() throws com.mendix.core.CoreException
	{
		return getValue_Series(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_Series
	 * @throws com.mendix.core.CoreException
	 */
	public final rencar.proxies.Series getValue_Series(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rencar.proxies.Series result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Value_Series.toString());
		if (identifier != null) {
			result = rencar.proxies.Series.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Value_Series
	 * @param value_series
	 */
	public final void setValue_Series(rencar.proxies.Series value_series)
	{
		setValue_Series(getContext(), value_series);
	}

	/**
	 * Set value of Value_Series
	 * @param context
	 * @param value_series
	 */
	public final void setValue_Series(com.mendix.systemwideinterfaces.core.IContext context, rencar.proxies.Series value_series)
	{
		if (value_series == null) {
			getMendixObject().setValue(context, MemberNames.Value_Series.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Value_Series.toString(), value_series.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Value_DashboardHelper
	 */
	public final rencar.proxies.DashboardHelper getValue_DashboardHelper() throws com.mendix.core.CoreException
	{
		return getValue_DashboardHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Value_DashboardHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final rencar.proxies.DashboardHelper getValue_DashboardHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rencar.proxies.DashboardHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Value_DashboardHelper.toString());
		if (identifier != null) {
			result = rencar.proxies.DashboardHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Value_DashboardHelper
	 * @param value_dashboardhelper
	 */
	public final void setValue_DashboardHelper(rencar.proxies.DashboardHelper value_dashboardhelper)
	{
		setValue_DashboardHelper(getContext(), value_dashboardhelper);
	}

	/**
	 * Set value of Value_DashboardHelper
	 * @param context
	 * @param value_dashboardhelper
	 */
	public final void setValue_DashboardHelper(com.mendix.systemwideinterfaces.core.IContext context, rencar.proxies.DashboardHelper value_dashboardhelper)
	{
		if (value_dashboardhelper == null) {
			getMendixObject().setValue(context, MemberNames.Value_DashboardHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Value_DashboardHelper.toString(), value_dashboardhelper.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return valueMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rencar.proxies.Value that = (rencar.proxies.Value) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
