// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class VehiclePicture extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.VehiclePicture";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		VehiclePicture_Vehicle("MasterData.VehiclePicture_Vehicle");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VehiclePicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected VehiclePicture(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vehiclePictureMendixObject)
	{
		super(context, vehiclePictureMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, vehiclePictureMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'VehiclePicture.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.VehiclePicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.VehiclePicture.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static masterdata.proxies.VehiclePicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.VehiclePicture(context, mendixObject);
	}

	public static masterdata.proxies.VehiclePicture load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.VehiclePicture.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.VehiclePicture> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> masterdata.proxies.VehiclePicture.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of VehiclePicture_Vehicle
	 */
	public final masterdata.proxies.Vehicle getVehiclePicture_Vehicle() throws com.mendix.core.CoreException
	{
		return getVehiclePicture_Vehicle(getContext());
	}

	/**
	 * @param context
	 * @return value of VehiclePicture_Vehicle
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.Vehicle getVehiclePicture_Vehicle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Vehicle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VehiclePicture_Vehicle.toString());
		if (identifier != null) {
			result = masterdata.proxies.Vehicle.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of VehiclePicture_Vehicle
	 * @param vehiclepicture_vehicle
	 */
	public final void setVehiclePicture_Vehicle(masterdata.proxies.Vehicle vehiclepicture_vehicle)
	{
		setVehiclePicture_Vehicle(getContext(), vehiclepicture_vehicle);
	}

	/**
	 * Set value of VehiclePicture_Vehicle
	 * @param context
	 * @param vehiclepicture_vehicle
	 */
	public final void setVehiclePicture_Vehicle(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Vehicle vehiclepicture_vehicle)
	{
		if (vehiclepicture_vehicle == null) {
			getMendixObject().setValue(context, MemberNames.VehiclePicture_Vehicle.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.VehiclePicture_Vehicle.toString(), vehiclepicture_vehicle.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.VehiclePicture that = (masterdata.proxies.VehiclePicture) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
