// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class VehicleUnit
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject vehicleUnitMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.VehicleUnit";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LicensePlate("LicensePlate"),
		VehicleUnit_Vehicle("MasterData.VehicleUnit_Vehicle"),
		CarSearch_VehicleUnit("Rencar.CarSearch_VehicleUnit");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VehicleUnit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected VehicleUnit(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vehicleUnitMendixObject)
	{
		if (vehicleUnitMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, vehicleUnitMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.vehicleUnitMendixObject = vehicleUnitMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'VehicleUnit.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static masterdata.proxies.VehicleUnit initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return masterdata.proxies.VehicleUnit.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static masterdata.proxies.VehicleUnit initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.VehicleUnit(context, mendixObject);
	}

	public static masterdata.proxies.VehicleUnit load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.VehicleUnit.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.VehicleUnit> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> masterdata.proxies.VehicleUnit.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of LicensePlate
	 */
	public final java.lang.String getLicensePlate()
	{
		return getLicensePlate(getContext());
	}

	/**
	 * @param context
	 * @return value of LicensePlate
	 */
	public final java.lang.String getLicensePlate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LicensePlate.toString());
	}

	/**
	 * Set value of LicensePlate
	 * @param licenseplate
	 */
	public final void setLicensePlate(java.lang.String licenseplate)
	{
		setLicensePlate(getContext(), licenseplate);
	}

	/**
	 * Set value of LicensePlate
	 * @param context
	 * @param licenseplate
	 */
	public final void setLicensePlate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String licenseplate)
	{
		getMendixObject().setValue(context, MemberNames.LicensePlate.toString(), licenseplate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of VehicleUnit_Vehicle
	 */
	public final masterdata.proxies.Vehicle getVehicleUnit_Vehicle() throws com.mendix.core.CoreException
	{
		return getVehicleUnit_Vehicle(getContext());
	}

	/**
	 * @param context
	 * @return value of VehicleUnit_Vehicle
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.Vehicle getVehicleUnit_Vehicle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Vehicle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VehicleUnit_Vehicle.toString());
		if (identifier != null) {
			result = masterdata.proxies.Vehicle.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of VehicleUnit_Vehicle
	 * @param vehicleunit_vehicle
	 */
	public final void setVehicleUnit_Vehicle(masterdata.proxies.Vehicle vehicleunit_vehicle)
	{
		setVehicleUnit_Vehicle(getContext(), vehicleunit_vehicle);
	}

	/**
	 * Set value of VehicleUnit_Vehicle
	 * @param context
	 * @param vehicleunit_vehicle
	 */
	public final void setVehicleUnit_Vehicle(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Vehicle vehicleunit_vehicle)
	{
		if (vehicleunit_vehicle == null) {
			getMendixObject().setValue(context, MemberNames.VehicleUnit_Vehicle.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.VehicleUnit_Vehicle.toString(), vehicleunit_vehicle.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CarSearch_VehicleUnit
	 */
	public final java.util.List<rencar.proxies.CarSearch> getCarSearch_VehicleUnit() throws com.mendix.core.CoreException
	{
		return getCarSearch_VehicleUnit(getContext());
	}

	/**
	 * @param context
	 * @return value of CarSearch_VehicleUnit
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<rencar.proxies.CarSearch> getCarSearch_VehicleUnit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<rencar.proxies.CarSearch> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.CarSearch_VehicleUnit.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(rencar.proxies.CarSearch.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of CarSearch_VehicleUnit
	 * @param carsearch_vehicleunit
	 */
	public final void setCarSearch_VehicleUnit(java.util.List<rencar.proxies.CarSearch> carsearch_vehicleunit)
	{
		setCarSearch_VehicleUnit(getContext(), carsearch_vehicleunit);
	}

	/**
	 * Set value of CarSearch_VehicleUnit
	 * @param context
	 * @param carsearch_vehicleunit
	 */
	public final void setCarSearch_VehicleUnit(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<rencar.proxies.CarSearch> carsearch_vehicleunit)
	{
		var identifiers = carsearch_vehicleunit
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.CarSearch_VehicleUnit.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return vehicleUnitMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.VehicleUnit that = (masterdata.proxies.VehicleUnit) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
