// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rest.proxies;

public class City
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "REST.City";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Nome("Nome"),
		City_Root("REST.City_Root"),
		Microrregiao_City("REST.Microrregiao_City"),
		Regiao_imediata_City("REST.Regiao_imediata_City");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public City(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected City(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cityMendixObject)
	{
		if (cityMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cityMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cityMendixObject = cityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'City.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rest.proxies.City initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rest.proxies.City.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static rest.proxies.City initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rest.proxies.City(context, mendixObject);
	}

	public static rest.proxies.City load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rest.proxies.City.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Nome
	 */
	public final java.lang.String getNome()
	{
		return getNome(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome
	 */
	public final java.lang.String getNome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome.toString());
	}

	/**
	 * Set value of Nome
	 * @param nome
	 */
	public final void setNome(java.lang.String nome)
	{
		setNome(getContext(), nome);
	}

	/**
	 * Set value of Nome
	 * @param context
	 * @param nome
	 */
	public final void setNome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome)
	{
		getMendixObject().setValue(context, MemberNames.Nome.toString(), nome);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of City_Root
	 */
	public final rest.proxies.Root getCity_Root() throws com.mendix.core.CoreException
	{
		return getCity_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of City_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final rest.proxies.Root getCity_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rest.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.City_Root.toString());
		if (identifier != null) {
			result = rest.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of City_Root
	 * @param city_root
	 */
	public final void setCity_Root(rest.proxies.Root city_root)
	{
		setCity_Root(getContext(), city_root);
	}

	/**
	 * Set value of City_Root
	 * @param context
	 * @param city_root
	 */
	public final void setCity_Root(com.mendix.systemwideinterfaces.core.IContext context, rest.proxies.Root city_root)
	{
		if (city_root == null) {
			getMendixObject().setValue(context, MemberNames.City_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.City_Root.toString(), city_root.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Microrregiao_City
	 */
	public final rest.proxies.Microrregiao getMicrorregiao_City() throws com.mendix.core.CoreException
	{
		return getMicrorregiao_City(getContext());
	}

	/**
	 * @param context
	 * @return value of Microrregiao_City
	 * @throws com.mendix.core.CoreException
	 */
	public final rest.proxies.Microrregiao getMicrorregiao_City(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rest.proxies.Microrregiao result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Microrregiao_City.toString());
		if (identifier != null) {
			result = rest.proxies.Microrregiao.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Microrregiao_City
	 * @param microrregiao_city
	 */
	public final void setMicrorregiao_City(rest.proxies.Microrregiao microrregiao_city)
	{
		setMicrorregiao_City(getContext(), microrregiao_city);
	}

	/**
	 * Set value of Microrregiao_City
	 * @param context
	 * @param microrregiao_city
	 */
	public final void setMicrorregiao_City(com.mendix.systemwideinterfaces.core.IContext context, rest.proxies.Microrregiao microrregiao_city)
	{
		if (microrregiao_city == null) {
			getMendixObject().setValue(context, MemberNames.Microrregiao_City.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Microrregiao_City.toString(), microrregiao_city.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Regiao_imediata_City
	 */
	public final rest.proxies.Regiao_imediata getRegiao_imediata_City() throws com.mendix.core.CoreException
	{
		return getRegiao_imediata_City(getContext());
	}

	/**
	 * @param context
	 * @return value of Regiao_imediata_City
	 * @throws com.mendix.core.CoreException
	 */
	public final rest.proxies.Regiao_imediata getRegiao_imediata_City(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rest.proxies.Regiao_imediata result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Regiao_imediata_City.toString());
		if (identifier != null) {
			result = rest.proxies.Regiao_imediata.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Regiao_imediata_City
	 * @param regiao_imediata_city
	 */
	public final void setRegiao_imediata_City(rest.proxies.Regiao_imediata regiao_imediata_city)
	{
		setRegiao_imediata_City(getContext(), regiao_imediata_city);
	}

	/**
	 * Set value of Regiao_imediata_City
	 * @param context
	 * @param regiao_imediata_city
	 */
	public final void setRegiao_imediata_City(com.mendix.systemwideinterfaces.core.IContext context, rest.proxies.Regiao_imediata regiao_imediata_city)
	{
		if (regiao_imediata_city == null) {
			getMendixObject().setValue(context, MemberNames.Regiao_imediata_City.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Regiao_imediata_City.toString(), regiao_imediata_city.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rest.proxies.City that = (rest.proxies.City) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
