// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rest.proxies;

public class Mesorregiao
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mesorregiaoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "REST.Mesorregiao";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Nome("Nome"),
		Mesorregiao_Microrregiao("REST.Mesorregiao_Microrregiao"),
		UF_Mesorregiao("REST.UF_Mesorregiao");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Mesorregiao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Mesorregiao(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mesorregiaoMendixObject)
	{
		if (mesorregiaoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, mesorregiaoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mesorregiaoMendixObject = mesorregiaoMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Mesorregiao.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rest.proxies.Mesorregiao initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rest.proxies.Mesorregiao.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static rest.proxies.Mesorregiao initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rest.proxies.Mesorregiao(context, mendixObject);
	}

	public static rest.proxies.Mesorregiao load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rest.proxies.Mesorregiao.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of _id
	 */
	public final java.lang.Integer get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.Integer get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.Integer _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Nome
	 */
	public final java.lang.String getNome()
	{
		return getNome(getContext());
	}

	/**
	 * @param context
	 * @return value of Nome
	 */
	public final java.lang.String getNome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Nome.toString());
	}

	/**
	 * Set value of Nome
	 * @param nome
	 */
	public final void setNome(java.lang.String nome)
	{
		setNome(getContext(), nome);
	}

	/**
	 * Set value of Nome
	 * @param context
	 * @param nome
	 */
	public final void setNome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nome)
	{
		getMendixObject().setValue(context, MemberNames.Nome.toString(), nome);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Mesorregiao_Microrregiao
	 */
	public final rest.proxies.Microrregiao getMesorregiao_Microrregiao() throws com.mendix.core.CoreException
	{
		return getMesorregiao_Microrregiao(getContext());
	}

	/**
	 * @param context
	 * @return value of Mesorregiao_Microrregiao
	 * @throws com.mendix.core.CoreException
	 */
	public final rest.proxies.Microrregiao getMesorregiao_Microrregiao(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rest.proxies.Microrregiao result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Mesorregiao_Microrregiao.toString());
		if (identifier != null) {
			result = rest.proxies.Microrregiao.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Mesorregiao_Microrregiao
	 * @param mesorregiao_microrregiao
	 */
	public final void setMesorregiao_Microrregiao(rest.proxies.Microrregiao mesorregiao_microrregiao)
	{
		setMesorregiao_Microrregiao(getContext(), mesorregiao_microrregiao);
	}

	/**
	 * Set value of Mesorregiao_Microrregiao
	 * @param context
	 * @param mesorregiao_microrregiao
	 */
	public final void setMesorregiao_Microrregiao(com.mendix.systemwideinterfaces.core.IContext context, rest.proxies.Microrregiao mesorregiao_microrregiao)
	{
		if (mesorregiao_microrregiao == null) {
			getMendixObject().setValue(context, MemberNames.Mesorregiao_Microrregiao.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Mesorregiao_Microrregiao.toString(), mesorregiao_microrregiao.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UF_Mesorregiao
	 */
	public final rest.proxies.UF getUF_Mesorregiao() throws com.mendix.core.CoreException
	{
		return getUF_Mesorregiao(getContext());
	}

	/**
	 * @param context
	 * @return value of UF_Mesorregiao
	 * @throws com.mendix.core.CoreException
	 */
	public final rest.proxies.UF getUF_Mesorregiao(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		rest.proxies.UF result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UF_Mesorregiao.toString());
		if (identifier != null) {
			result = rest.proxies.UF.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UF_Mesorregiao
	 * @param uf_mesorregiao
	 */
	public final void setUF_Mesorregiao(rest.proxies.UF uf_mesorregiao)
	{
		setUF_Mesorregiao(getContext(), uf_mesorregiao);
	}

	/**
	 * Set value of UF_Mesorregiao
	 * @param context
	 * @param uf_mesorregiao
	 */
	public final void setUF_Mesorregiao(com.mendix.systemwideinterfaces.core.IContext context, rest.proxies.UF uf_mesorregiao)
	{
		if (uf_mesorregiao == null) {
			getMendixObject().setValue(context, MemberNames.UF_Mesorregiao.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UF_Mesorregiao.toString(), uf_mesorregiao.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mesorregiaoMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rest.proxies.Mesorregiao that = (rest.proxies.Mesorregiao) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
