// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package rest.proxies;

public class Xmlcep
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject xmlcepMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "REST.Xmlcep";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Cep("Cep"),
		Logradouro("Logradouro"),
		Complemento("Complemento"),
		Bairro("Bairro"),
		Localidade("Localidade"),
		Uf("Uf"),
		Ibge("Ibge"),
		Gia("Gia"),
		Ddd("Ddd"),
		Siafi("Siafi");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Xmlcep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Xmlcep(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject xmlcepMendixObject)
	{
		if (xmlcepMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, xmlcepMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.xmlcepMendixObject = xmlcepMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Xmlcep.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static rest.proxies.Xmlcep initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return rest.proxies.Xmlcep.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static rest.proxies.Xmlcep initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new rest.proxies.Xmlcep(context, mendixObject);
	}

	public static rest.proxies.Xmlcep load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return rest.proxies.Xmlcep.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Cep
	 */
	public final java.lang.String getCep()
	{
		return getCep(getContext());
	}

	/**
	 * @param context
	 * @return value of Cep
	 */
	public final java.lang.String getCep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cep.toString());
	}

	/**
	 * Set value of Cep
	 * @param cep
	 */
	public final void setCep(java.lang.String cep)
	{
		setCep(getContext(), cep);
	}

	/**
	 * Set value of Cep
	 * @param context
	 * @param cep
	 */
	public final void setCep(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cep)
	{
		getMendixObject().setValue(context, MemberNames.Cep.toString(), cep);
	}

	/**
	 * @return value of Logradouro
	 */
	public final java.lang.String getLogradouro()
	{
		return getLogradouro(getContext());
	}

	/**
	 * @param context
	 * @return value of Logradouro
	 */
	public final java.lang.String getLogradouro(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Logradouro.toString());
	}

	/**
	 * Set value of Logradouro
	 * @param logradouro
	 */
	public final void setLogradouro(java.lang.String logradouro)
	{
		setLogradouro(getContext(), logradouro);
	}

	/**
	 * Set value of Logradouro
	 * @param context
	 * @param logradouro
	 */
	public final void setLogradouro(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String logradouro)
	{
		getMendixObject().setValue(context, MemberNames.Logradouro.toString(), logradouro);
	}

	/**
	 * @return value of Complemento
	 */
	public final java.lang.String getComplemento()
	{
		return getComplemento(getContext());
	}

	/**
	 * @param context
	 * @return value of Complemento
	 */
	public final java.lang.String getComplemento(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Complemento.toString());
	}

	/**
	 * Set value of Complemento
	 * @param complemento
	 */
	public final void setComplemento(java.lang.String complemento)
	{
		setComplemento(getContext(), complemento);
	}

	/**
	 * Set value of Complemento
	 * @param context
	 * @param complemento
	 */
	public final void setComplemento(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String complemento)
	{
		getMendixObject().setValue(context, MemberNames.Complemento.toString(), complemento);
	}

	/**
	 * @return value of Bairro
	 */
	public final java.lang.String getBairro()
	{
		return getBairro(getContext());
	}

	/**
	 * @param context
	 * @return value of Bairro
	 */
	public final java.lang.String getBairro(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Bairro.toString());
	}

	/**
	 * Set value of Bairro
	 * @param bairro
	 */
	public final void setBairro(java.lang.String bairro)
	{
		setBairro(getContext(), bairro);
	}

	/**
	 * Set value of Bairro
	 * @param context
	 * @param bairro
	 */
	public final void setBairro(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bairro)
	{
		getMendixObject().setValue(context, MemberNames.Bairro.toString(), bairro);
	}

	/**
	 * @return value of Localidade
	 */
	public final java.lang.String getLocalidade()
	{
		return getLocalidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Localidade
	 */
	public final java.lang.String getLocalidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Localidade.toString());
	}

	/**
	 * Set value of Localidade
	 * @param localidade
	 */
	public final void setLocalidade(java.lang.String localidade)
	{
		setLocalidade(getContext(), localidade);
	}

	/**
	 * Set value of Localidade
	 * @param context
	 * @param localidade
	 */
	public final void setLocalidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String localidade)
	{
		getMendixObject().setValue(context, MemberNames.Localidade.toString(), localidade);
	}

	/**
	 * @return value of Uf
	 */
	public final java.lang.String getUf()
	{
		return getUf(getContext());
	}

	/**
	 * @param context
	 * @return value of Uf
	 */
	public final java.lang.String getUf(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Uf.toString());
	}

	/**
	 * Set value of Uf
	 * @param uf
	 */
	public final void setUf(java.lang.String uf)
	{
		setUf(getContext(), uf);
	}

	/**
	 * Set value of Uf
	 * @param context
	 * @param uf
	 */
	public final void setUf(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uf)
	{
		getMendixObject().setValue(context, MemberNames.Uf.toString(), uf);
	}

	/**
	 * @return value of Ibge
	 */
	public final java.lang.Integer getIbge()
	{
		return getIbge(getContext());
	}

	/**
	 * @param context
	 * @return value of Ibge
	 */
	public final java.lang.Integer getIbge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ibge.toString());
	}

	/**
	 * Set value of Ibge
	 * @param ibge
	 */
	public final void setIbge(java.lang.Integer ibge)
	{
		setIbge(getContext(), ibge);
	}

	/**
	 * Set value of Ibge
	 * @param context
	 * @param ibge
	 */
	public final void setIbge(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ibge)
	{
		getMendixObject().setValue(context, MemberNames.Ibge.toString(), ibge);
	}

	/**
	 * @return value of Gia
	 */
	public final java.lang.Integer getGia()
	{
		return getGia(getContext());
	}

	/**
	 * @param context
	 * @return value of Gia
	 */
	public final java.lang.Integer getGia(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Gia.toString());
	}

	/**
	 * Set value of Gia
	 * @param gia
	 */
	public final void setGia(java.lang.Integer gia)
	{
		setGia(getContext(), gia);
	}

	/**
	 * Set value of Gia
	 * @param context
	 * @param gia
	 */
	public final void setGia(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer gia)
	{
		getMendixObject().setValue(context, MemberNames.Gia.toString(), gia);
	}

	/**
	 * @return value of Ddd
	 */
	public final java.lang.Integer getDdd()
	{
		return getDdd(getContext());
	}

	/**
	 * @param context
	 * @return value of Ddd
	 */
	public final java.lang.Integer getDdd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ddd.toString());
	}

	/**
	 * Set value of Ddd
	 * @param ddd
	 */
	public final void setDdd(java.lang.Integer ddd)
	{
		setDdd(getContext(), ddd);
	}

	/**
	 * Set value of Ddd
	 * @param context
	 * @param ddd
	 */
	public final void setDdd(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ddd)
	{
		getMendixObject().setValue(context, MemberNames.Ddd.toString(), ddd);
	}

	/**
	 * @return value of Siafi
	 */
	public final java.lang.Integer getSiafi()
	{
		return getSiafi(getContext());
	}

	/**
	 * @param context
	 * @return value of Siafi
	 */
	public final java.lang.Integer getSiafi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Siafi.toString());
	}

	/**
	 * Set value of Siafi
	 * @param siafi
	 */
	public final void setSiafi(java.lang.Integer siafi)
	{
		setSiafi(getContext(), siafi);
	}

	/**
	 * Set value of Siafi
	 * @param context
	 * @param siafi
	 */
	public final void setSiafi(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer siafi)
	{
		getMendixObject().setValue(context, MemberNames.Siafi.toString(), siafi);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return xmlcepMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final rest.proxies.Xmlcep that = (rest.proxies.Xmlcep) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
